DROP TABLE IF EXISTS Role;
CREATE TABLE IF NOT EXISTS Role(ID INT PRIMARY KEY, NAME VARCHAR(255));
INSERT INTO Role VALUES (1, 'ROLE_ADMIN');
INSERT INTO Role VALUES (2, 'ROLE_USER');
INSERT INTO Role VALUES (3, 'ROLE_GUEST');